---
framework: jest
preRun:
     command:
        - npm install
preMerge:
  pattern:
    - "./test/*/*.js"
    - "./test/*.js"
postMerge:
  pattern: 
    - "./test/*/*.js"
    - "./test/*.js"
postRun:
     command:
        - npm --version
version: 1.0
